// CHR-ROM Map & decos indexes
// Generated by rle53mapchrrom.exe v0.1 20171113
// Copyleft 2017 by The Mojon Twins

// Map # 0 read from level0.map (5x5)

// Definitions

#define MAP_00_CHRROM    1
#define MAP_00_BASE      0x0000
#define MAP_00_W         5
#define MAP_00_H         5
#define MAP_00_MAXPANTS  25

// Screens index

const unsigned int map_00_scr_offsets [] = {
	MAP_00_BASE + 0x0000, MAP_00_BASE + 0x0069, 
	MAP_00_BASE + 0x00B3, MAP_00_BASE + 0x012F, 
	MAP_00_BASE + 0x019D, MAP_00_BASE + 0x021F, 
	MAP_00_BASE + 0x02A3, MAP_00_BASE + 0x02F9, 
	MAP_00_BASE + 0x0385, MAP_00_BASE + 0x03E1, 
	MAP_00_BASE + 0x0456, MAP_00_BASE + 0x04BB, 
	MAP_00_BASE + 0x0537, MAP_00_BASE + 0x05D4, 
	MAP_00_BASE + 0x064E, MAP_00_BASE + 0x06B2, 
	MAP_00_BASE + 0x073F, MAP_00_BASE + 0x07AD, 
	MAP_00_BASE + 0x0830, MAP_00_BASE + 0x08B8, 
	MAP_00_BASE + 0x092D, MAP_00_BASE + 0x09C1, 
	MAP_00_BASE + 0x0A35, MAP_00_BASE + 0x0A9D, 
	MAP_00_BASE + 0x0B02
};

// Total screens size in bytes is 2945

// Locks
// These tiles are locks:  15
const unsigned char map_00_locks [] = {
	0x02, 0x78, 0x0a, 0x92, 0x13, 0x22
};

// Map # 1 read from level1.map (5x5)

// Definitions

#define MAP_01_CHRROM    1
#define MAP_01_BASE      0x0B81
#define MAP_01_W         5
#define MAP_01_H         5
#define MAP_01_MAXPANTS  25

// Screens index

const unsigned int map_01_scr_offsets [] = {
	MAP_01_BASE + 0x0000, MAP_01_BASE + 0x0071, 
	MAP_01_BASE + 0x00E7, MAP_01_BASE + 0x015B, 
	MAP_01_BASE + 0x01D7, MAP_01_BASE + 0x0252, 
	MAP_01_BASE + 0x02E0, MAP_01_BASE + 0x0366, 
	MAP_01_BASE + 0x03E1, MAP_01_BASE + 0x046A, 
	MAP_01_BASE + 0x04FD, MAP_01_BASE + 0x0580, 
	MAP_01_BASE + 0x05FD, MAP_01_BASE + 0x0686, 
	MAP_01_BASE + 0x070B, MAP_01_BASE + 0x07A1, 
	MAP_01_BASE + 0x0824, MAP_01_BASE + 0x08A7, 
	MAP_01_BASE + 0x0936, MAP_01_BASE + 0x09CC, 
	MAP_01_BASE + 0x0A5D, MAP_01_BASE + 0x0AEE, 
	MAP_01_BASE + 0x05FD, MAP_01_BASE + 0x0B75, 
	MAP_01_BASE + 0x0C13
};

// Total screens size in bytes is 3237

// Locks
// These tiles are locks:  15 30
const unsigned char map_01_locks [] = {
	0x03, 0x1f, 0x01, 0xaf, 0x02, 0xaf, 0x04, 0xbb, 0x08, 0x60, 0x06, 0x90, 0x09, 0xa0, 0x0a, 0x58, 0x0e, 0x50, 0x0b, 0x60, 0x0d, 0x62, 0x10, 0x07, 0x13, 0x0d, 0x12, 0x2f, 0x11, 0x9f, 0x0f, 0xbd, 0x18, 0x50, 0x15, 0x6d
};

// Map # 2 read from level2.map (5x5)

// Definitions

#define MAP_02_CHRROM    1
#define MAP_02_BASE      0x1826
#define MAP_02_W         5
#define MAP_02_H         5
#define MAP_02_MAXPANTS  25

// Screens index

const unsigned int map_02_scr_offsets [] = {
	MAP_02_BASE + 0x0000, MAP_02_BASE + 0x0087, 
	MAP_02_BASE + 0x00D7, MAP_02_BASE + 0x0110, 
	MAP_02_BASE + 0x0138, MAP_02_BASE + 0x0179, 
	MAP_02_BASE + 0x01CC, MAP_02_BASE + 0x0224, 
	MAP_02_BASE + 0x025F, MAP_02_BASE + 0x02A4, 
	MAP_02_BASE + 0x02FB, MAP_02_BASE + 0x037A, 
	MAP_02_BASE + 0x03D6, MAP_02_BASE + 0x0430, 
	MAP_02_BASE + 0x04A2, MAP_02_BASE + 0x0000, 
	MAP_02_BASE + 0x0514, MAP_02_BASE + 0x056F, 
	MAP_02_BASE + 0x05B8, MAP_02_BASE + 0x060D, 
	MAP_02_BASE + 0x0179, MAP_02_BASE + 0x0682, 
	MAP_02_BASE + 0x06C2, MAP_02_BASE + 0x06EE, 
	MAP_02_BASE + 0x0751
};

// Total screens size in bytes is 1949

// Locks
// These tiles are locks:  15 31
const unsigned char map_02_locks [] = {
	0x00, 0x54, 0x0d, 0xaf, 0x0f, 0x54, 0x13, 0x90
};

// Map # 3 read from leveli.map (3x1)

// Definitions

#define MAP_03_CHRROM    2
#define MAP_03_BASE      0x0000
#define MAP_03_W         3
#define MAP_03_H         1
#define MAP_03_MAXPANTS  3

// Screens index

const unsigned int map_03_scr_offsets [] = {
	MAP_03_BASE + 0x0000, MAP_03_BASE + 0x005A, 
	MAP_03_BASE + 0x00A5
};

// Total screens size in bytes is 271

// Map # 4 read from level3.map (5x5)

// Definitions

#define MAP_04_CHRROM    2
#define MAP_04_BASE      0x010F
#define MAP_04_W         5
#define MAP_04_H         5
#define MAP_04_MAXPANTS  25

// Screens index

const unsigned int map_04_scr_offsets [] = {
	MAP_04_BASE + 0x0000, 0                   , 
	0                   , 0                   , 
	0                   , MAP_04_BASE + 0x007F, 
	0                   , 0                   , 
	0                   , 0                   , 
	MAP_04_BASE + 0x00EF, MAP_04_BASE + 0x018A, 
	MAP_04_BASE + 0x0212, MAP_04_BASE + 0x0277, 
	MAP_04_BASE + 0x02DB, MAP_04_BASE + 0x0328, 
	MAP_04_BASE + 0x03AA, MAP_04_BASE + 0x042E, 
	MAP_04_BASE + 0x04A7, MAP_04_BASE + 0x0519, 
	MAP_04_BASE + 0x05A3, MAP_04_BASE + 0x0611, 
	MAP_04_BASE + 0x0686, MAP_04_BASE + 0x06F5, 
	MAP_04_BASE + 0x076F
};

// Total screens size in bytes is 1972

// Locks
// These tiles are locks:  15 31
const unsigned char map_04_locks [] = {
	0x00, 0xb8, 0x05, 0xb4, 0x0a, 0x2f, 0x0d, 0x50, 0x0e, 0x5b, 0x0b, 0x9b, 0x0a, 0xb5, 0x0c, 0xb8, 0x12, 0x08, 0x13, 0x08, 0x12, 0x5f, 0x0f, 0xbd, 0x12, 0xb7, 0x15, 0x08, 0x17, 0x60, 0x18, 0x97, 0x16, 0xa0
};

// Map # 5 read from level4.map (5x5)

// Definitions

#define MAP_05_CHRROM    2
#define MAP_05_BASE      0x08C3
#define MAP_05_W         5
#define MAP_05_H         5
#define MAP_05_MAXPANTS  25

// Screens index

const unsigned int map_05_scr_offsets [] = {
	MAP_05_BASE + 0x0000, MAP_05_BASE + 0x004F, 
	MAP_05_BASE + 0x00A3, MAP_05_BASE + 0x00F3, 
	MAP_05_BASE + 0x015E, MAP_05_BASE + 0x01BC, 
	MAP_05_BASE + 0x0210, MAP_05_BASE + 0x0253, 
	MAP_05_BASE + 0x02C7, MAP_05_BASE + 0x032F, 
	MAP_05_BASE + 0x036E, MAP_05_BASE + 0x0210, 
	MAP_05_BASE + 0x03DE, MAP_05_BASE + 0x0441, 
	MAP_05_BASE + 0x04AB, MAP_05_BASE + 0x0526, 
	MAP_05_BASE + 0x0570, MAP_05_BASE + 0x05AD, 
	MAP_05_BASE + 0x0629, MAP_05_BASE + 0x066A, 
	MAP_05_BASE + 0x06AF, MAP_05_BASE + 0x0730, 
	MAP_05_BASE + 0x0790, MAP_05_BASE + 0x07F2, 
	MAP_05_BASE + 0x083F
};

// Total screens size in bytes is 2197

