// ..\dev\assets\enemsi.h
// Generated by eneexp3c.exe v0.1 [20170405]
// Copyleft 2016 The Mojon Twins

// Enems structure is {T YX1 YX2 P} x 3 x MAP_W x MAP_H
// y coordinates are adjusted by 1 positions

const unsigned char enems_i_02 [] = {
	0x10, 0x46, 0x49, 0x01, 0
};

const unsigned char * const enems_i [] = {
	0, 0, enems_i_02
};

// Bytes: 11 vs. MAP_WxMAP_Hx12 = 36 (30%)

#define MAX_ENEMS_I_TYPE_10	1

// Hotspots structure is {T YX} x MAP_W x MAP_H
const unsigned char hotspots_i [] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00};

#define MAX_HOTSPOTS_I_TYPE_0	3
