// CHR-ROM Map & decos indexes
// Generated by rle53mapchrrom.exe v0.1 20171113
// Copyleft 2017 by The Mojon Twins

// Map # 0 read from level0.map (5x5)

// Size = 81 bytes.
// Size = 65 bytes.
// Size = 132 bytes.
// Size = 84 bytes.
// Size = 92 bytes.
// Size = 99 bytes.
// Size = 59 bytes.
// Size = 153 bytes.
// Size = 85 bytes.
// Size = 117 bytes.
// Size = 81 bytes.
// Size = 124 bytes.
// Size = 142 bytes.
// Size = 141 bytes.
// Size = 111 bytes.
// Size = 140 bytes.
// Size = 102 bytes.
// Size = 122 bytes.
// Size = 159 bytes.
// Size = 125 bytes.
// Size = 102 bytes.
// Size = 88 bytes.
// Size = 123 bytes.
// Size = 146 bytes.
// Size = 159 bytes.
// Definitions

#define MAP_00_CHRROM    1
#define MAP_00_BASE      0x0000
#define MAP_00_W         5
#define MAP_00_H         5
#define MAP_00_MAXPANTS  25

// Screens index

const unsigned int map_00_scr_offsets [] = {
	MAP_00_BASE + 0x0000, MAP_00_BASE + 0x0051, 
	MAP_00_BASE + 0x0092, MAP_00_BASE + 0x0116, 
	MAP_00_BASE + 0x016A, MAP_00_BASE + 0x01C6, 
	MAP_00_BASE + 0x0229, MAP_00_BASE + 0x0264, 
	MAP_00_BASE + 0x02FD, MAP_00_BASE + 0x0352, 
	MAP_00_BASE + 0x03C7, MAP_00_BASE + 0x0418, 
	MAP_00_BASE + 0x0494, MAP_00_BASE + 0x0522, 
	MAP_00_BASE + 0x05AF, MAP_00_BASE + 0x061E, 
	MAP_00_BASE + 0x06AA, MAP_00_BASE + 0x0710, 
	MAP_00_BASE + 0x078A, MAP_00_BASE + 0x0829, 
	MAP_00_BASE + 0x08A6, MAP_00_BASE + 0x090C, 
	MAP_00_BASE + 0x0964, MAP_00_BASE + 0x09DF, 
	MAP_00_BASE + 0x0A71
};

// Total screens size in bytes is 2832

// Locks
// These tiles are locks:  15
const unsigned char map_00_locks [] = {
	0x02, 0x78, 0x0a, 0x92, 0x13, 0x22
};

// Map # 1 read from level1.map (5x5)

// Screen 00 is empty.
// Screen 01 is empty.
// Screen 02 is empty.
// Screen 03 is empty.
// Screen 04 is empty.
// Screen 05 is empty.
// Screen 06 is empty.
// Screen 07 is empty.
// Screen 08 is empty.
// Screen 09 is empty.
// Size = 97 bytes.
// Size = 85 bytes.
// Screen 0c is empty.
// Size = 88 bytes.
// Size = 85 bytes.
// Size = 85 bytes.
// Size = 77 bytes.
// Size = 87 bytes.
// Size = 99 bytes.
// Size = 102 bytes.
// Size = 100 bytes.
// Size = 79 bytes.
// Screen 16 is a copy of screen 15.
// Size = 78 bytes.
// Size = 78 bytes.
// Definitions

#define MAP_01_CHRROM    1
#define MAP_01_BASE      0x0B10
#define MAP_01_W         5
#define MAP_01_H         5
#define MAP_01_MAXPANTS  25

// Screens index

const unsigned int map_01_scr_offsets [] = {
	0                   , 0                   , 
	0                   , 0                   , 
	0                   , 0                   , 
	0                   , 0                   , 
	0                   , 0                   , 
	MAP_01_BASE + 0x0000, MAP_01_BASE + 0x0061, 
	0                   , MAP_01_BASE + 0x00B6, 
	MAP_01_BASE + 0x010E, MAP_01_BASE + 0x0163, 
	MAP_01_BASE + 0x01B8, MAP_01_BASE + 0x0205, 
	MAP_01_BASE + 0x025C, MAP_01_BASE + 0x02BF, 
	MAP_01_BASE + 0x0325, MAP_01_BASE + 0x0389, 
	MAP_01_BASE + 0x0389, MAP_01_BASE + 0x03D8, 
	MAP_01_BASE + 0x0426
};

// Total screens size in bytes is 1140

// Locks
// These tiles are locks:  15 30
const unsigned char map_01_locks [] = {
	0x0a, 0x58, 0x0e, 0x50, 0x0b, 0x60, 0x0d, 0x62, 0x10, 0x07, 0x13, 0x0d, 0x12, 0x2f, 0x11, 0x9f, 0x0f, 0xbd, 0x18, 0x50
};

